[common]
build_flags =
	-D VERSION=0.0.3

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags = -D PLATFORM_MEGA2560
lib_extra_dirs = ../
lib_deps = core

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -D PLATFORM_ARDUINO
lib_ignore =
	fractonica-mega2560display
lib_extra_dirs = ../
lib_deps = core

[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.03/platform-espressif32.zip
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
lib_extra_dirs = ../
lib_deps =
    esp32-camera
    mathertel/RotaryEncoder@^1.6.0
    fractonica-core
    SD
    SD_MMC
	fractonica-hardware

build_flags =
    -D PLATFORM_ESP32
    -std=gnu++17
build_unflags = -std=gnu++11
monitor_speed = 115200
lib_ignore =
    fractonica-mega2560display